[servicenow_latest_incident_status]
field.UID = string
field.short_description = string
field.status = string
disabled = 0

[servicenow_latest_incident_status_2]
field.short_description = string
field.status = string
