[dev_ad_idx]
coldPath = $SPLUNK_DB/dev_ad_idx/colddb
homePath = $SPLUNK_DB/dev_ad_idx/db
maxTotalDataSizeMB = 512000
thawedPath = $SPLUNK_DB/dev_ad_idx/thaweddb

[dev_dns_idx]
coldPath = $SPLUNK_DB/dev_dns_idx/colddb
homePath = $SPLUNK_DB/dev_dns_idx/db
maxTotalDataSizeMB = 512000
thawedPath = $SPLUNK_DB/dev_dns_idx/thaweddb

[dev_openvpn_idx]
coldPath = $SPLUNK_DB/dev_openvpn_idx/colddb
homePath = $SPLUNK_DB/dev_openvpn_idx/db
maxTotalDataSizeMB = 512000
thawedPath = $SPLUNK_DB/dev_openvpn_idx/thaweddb

[attack_data]
coldPath = $SPLUNK_DB/attack_data/colddb
homePath = $SPLUNK_DB/attack_data/db
maxTotalDataSizeMB = 512000
thawedPath = $SPLUNK_DB/attack_data/thaweddb

[access_demo_idx]
coldPath = $SPLUNK_DB/access_demo_idx/colddb
homePath = $SPLUNK_DB/access_demo_idx/db
maxTotalDataSizeMB = 512000
thawedPath = $SPLUNK_DB/access_demo_idx/thaweddb

[softmania_aws_monitoring]
coldPath = $SPLUNK_DB/softmania_aws_monitoring/colddb
homePath = $SPLUNK_DB/softmania_aws_monitoring/db
maxTotalDataSizeMB = 512000
thawedPath = $SPLUNK_DB/softmania_aws_monitoring/thaweddb

[sm_aws_monitoring]
coldPath = $SPLUNK_DB/sm_aws_monitoring/colddb
homePath = $SPLUNK_DB/sm_aws_monitoring/db
maxTotalDataSizeMB = 512000
thawedPath = $SPLUNK_DB/sm_aws_monitoring/thaweddb

[linux_snmp]
coldPath = $SPLUNK_DB/linux_snmp/colddb
homePath = $SPLUNK_DB/linux_snmp/db
maxTotalDataSizeMB = 512000
thawedPath = $SPLUNK_DB/linux_snmp/thaweddb

[linux_idx]
coldPath = $SPLUNK_DB/linux_idx/colddb
homePath = $SPLUNK_DB/linux_idx/db
maxTotalDataSizeMB = 512000
thawedPath = $SPLUNK_DB/linux_idx/thaweddb
