#   Version 9.2.0

[script://./bin/quarantine_files.py]
python.version = python3
interval = * * * * *
passAuth = splunk-system-user
run_only_one = false
disabled = false

[splunktcp://9997]
connection_host = ip

[splunktcp://9996]
connection_host = ip

