[geo_us_states]
external_type = geo
filename = geo_us_states.kmz

[geo_countries]
external_type = geo
filename = geo_countries.kmz

[geo_attr_us_states]
filename = geo_attr_us_states.csv

[geo_attr_countries]
filename = geo_attr_countries.csv

[geo_hex]
external_type=geo_hex

[failed_login_history]
batch_index_query = 0
case_sensitive_match = 1
filename = failed_login_history.csv

[host_whitelist_4625]
batch_index_query = 0
case_sensitive_match = 1
filename = host_whitelist_4625.csv

[servicenow_latest_incident_status]
collection = servicenow_latest_incident_status
external_type = kvstore
fields_list = UID,status,short_description

[access_lookup]
batch_index_query = 0
case_sensitive_match = 0
default_match = noaccess
filename = access_lookup.csv
max_matches = 3

[http_status_full_mapping]
batch_index_query = 0
case_sensitive_match = 1
filename = http_status_full_mapping.csv

[servicenow_incident_status_2]
collection = servicenow_latest_incident_status_2
external_type = kvstore
fields_list = status, short_description

